name: build images

on:
  push:

jobs:
  libc-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/rcore-os/rcore-fs.git rcore-fs-fuse

      - uses: actions/checkout@v3
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v3
        with: 
          path: toolchain/riscv64--musl--bleeding-edge-2020.08-1
          key: toolchain-rv64

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain

      - name: build images
        run: |
          make image FS=fat32
          make image FS=sfs

      - name: deloy images
        run: |
          mkdir public
          mv *.img public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
