name: build images

on:
  push:

jobs:
  libc-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v3
        with: 
          path: toolchain/riscv64--musl--bleeding-edge-2020.08-1
          key: toolchain-rv64

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain

      - name: build images
        run: make image

      - name: deloy images
        run: |
          mkdir public
          cp fat32.img public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public