name: build images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [x86_64, riscv64, aarch64]
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/rcore-os/rcore-fs.git rcore-fs-fuse

      - uses: actions/checkout@v3
      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v3
        with: 
          path: toolchain/${{matrix.arch}}--musl--bleeding-edge
          key: toolchain-${{matrix.arch}}

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain ARCH=${{matrix.arch}}

      - name: build images
        run: |
          sudo apt update && sudo apt install qemu-utils
          make image FS=fat32 ARCH=${{matrix.arch}}
          make image FS=sfs ARCH=${{matrix.arch}}

      - name: Upload images
        uses: actions/upload-artifact@v3
        with: 
          name: images
          path: |
            sfs_${{matrix.arch}}.img
            ${{matrix.arch}}.img


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download images
        uses: actions/download-artifact@v3
        with:
          name: images
      - name: generate the output dir
        run: |
          mkdir public
          mv *.img public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public