name: Test CI

on:
  push:

jobs:
  libc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ''

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src, llvm-tools-preview

      - name: Install python dependencies and submodule
        run: |
          pip3 install -r script/requirements.txt
          git submodule update --init

      - name: Run libc test
        run: make