name: Test CI

on:
  push:

env:
  qemu_version: 7.0.0

jobs:
  libc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ''

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src, llvm-tools-preview

      - name: Install python dependencies and submodule
        run: |
          pip3 install -r script/requirements.txt
          git submodule update --init
          sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Cache Qemu
        id: cache-qemu
        uses: actions/cache@v3
        with:
          path: qemu-${{env.qemu_version}}
          key: qemu-${{env.qemu_version}}

      - name: Download and Compile Qemu
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        run: .github/scripts/make-qemu.sh ${{env.qemu_version}}

      - name: Install Qemu
        run: |
          cd qemu-${{env.qemu_version}} && sudo make install
          qemu-system-riscv64 --version

      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v3
        with: 
          path: toolchain/riscv64--musl--bleeding-edge-2020.08-1
          key: toolchain-rv64

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make toolchain
      
      - name: Run libc test
        run: make test

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: output