name: Test CI

on:
  push:

jobs:
  libc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ''

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rust-src, llvm-tools-preview

      - name: Install python dependencies and submodule
        run: |
          pip3 install -r script/requirements.txt
          git submodule update --init

      - name: Install qemu
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build
          .github/scripts/make-qemu.sh 7.0.0
          cd qemu-7.0.0 && sudo make install
          qemu-system-riscv64 --version

      - name: Run libc test
        run: make